### ISSUE TITLE
textScaleFactor in headerText not possible

### ISSUE THREAD

**Issue by heeshala** [GotJimmy/accordion#1]
It is not possible to textScaleFactor:1.0; 

The content is possible as it is a Text() but as the header is a string it is not possible

Is there any appropriate solution ?

**Comment by GotJimmy** [comment]
True. But have you tried `headerTextStyle: TextStyle(fontSize: 50)` which can be applied to both the parent `Accordion` as well as each `AccordionSection`?

**Comment by heeshala** [comment]
> True. But have you tried `headerTextStyle: TextStyle(fontSize: 50)` which can be applied to both the parent `Accordion` as well as each `AccordionSection`?

Yes i have applied a font size.
The issue is that when device font size changes content get diatorted so the option is to use textScaleFactor

**Comment by GotJimmy** [comment]
Can you send me a screenshot of the distortion with the settings for device font size and header font size?

**Comment by heeshala** [comment]
I used 17 as font size
When the device font size is maximized the header also get larger

**Comment by GotJimmy** [comment]
Ok, I see your point. I will add a `headerTextScaleFactor` in the next version.
However, in the meantime you could set the font size to `fontSize / textScaleFactor`. This should basically have the same effect.

**Comment by GotJimmy** [comment]
Please see `header` parameter in new version 2.0.0
