### ISSUE TITLE
The element type 'AccordionSectionWidget' can't be assigned to the list type 'AccordionSection'.

### ISSUE THREAD

**Issue by Akwasititus** [GotJimmy/accordion#11]
AccordionSectionWidget(
            headerr: Text('*124#'),
            contentt: Text('Balance enquiry. Check your credit balance.'),
            open: false,
          ), // the error is coming from here

//Extrated widget
class AccordionSectionWidget extends StatelessWidget {
  final Text headerr;
  final Text contentt;
  final bool open;
  const AccordionSectionWidget(header,
      {required this.headerr, required this.contentt, required this.open});
  @override
  Widget build(BuildContext context) {
    return AccordionSection(
        contentBorderWidth: 3,
        isOpen: false,
        header: headerr,
        // style: TextStyle(color: Colors.white, fontSize: 17)

        content: contentt);
  }
}

**Comment by GotJimmy** [comment]
Try AccordionSection instead of AccordionSectionWidget.

**Comment by Akwasititus** [comment]
ok boss

**Comment by GotJimmy** [comment]
Did you get it working?
