### ISSUE TITLE
Option to disable animations.

### ISSUE THREAD

**Issue by thunderrous** [GotJimmy/accordion#12]
Hello.

Could you please consider adding a parameter to disable animations? It doesn't fit with the rest of my app.

Thank you for creating this package.

**Comment by GotJimmy** [comment]
I'm pretty reluctant to do this since it seems like a step backward. IMO, a good and modern UI needs animation not only for the looks, but to aid users in seeing what's changing.

**Comment by thunderrous** [comment]
I think it's pretty obvious when something like this changes. 

It's just a parameter to add/remove it to their liking, not removing the animation completely.

**Comment by GotJimmy** [comment]
Alright, if it's important to you. But it will take at least a week since I'm very busy right now.

**Comment by thunderrous** [comment]
I've found something else that's better suited to my app so no need. Thanks anyways.
