### ISSUE TITLE
Minor enhancements!

### ISSUE THREAD

**Issue by mikah22** [GotJimmy/accordion#13]
Thank you for making this great library available to the flutter community. Very thoughtfully made with fantastic attention to detail. I just have a few thoughts about how we could make it better:

1. Is it possible to provide an option to change color of the up / down (open/close) icon to the right? Right now it's fixed to white.
2. Option to have a separate color for open sections so that it stands out.
3. Another animation option. For example, when a section is opened, the content view just slides down from the header and when closed the content view slides back into the header.
4. Set Duration of the animation and when duration is 0 there should be no animation.
5. Option to include a Haptic feedback when header is tapped to open/close

**Comment by GotJimmy** [comment]
Thanks :)

1) it's already possible on both `Accordion` (for all sections) as well as individually for `AccordionSection`. Just set this parameter:
`          rightIcon: Icon(
                Icons.keyboard_arrow_down,
                size: 20,
                color: Colors.red,
            ),
`

2) technically already possible, but I just added `headerBackgroundColorOpened` parameter for both `Accordion` and `AccordionSection` to change the background color of the header when opened.

3) good idea. I'll make a note for future implementation of this.

4) I'll have another look at that. The duration is actually carefully timed, but I know by now that some folks want to play with the duration. You may want to try different settings for `scrollIntoViewOfItems` -- that may already be what you want.

5) good idea.

Version 2.2.0 will be out in the next few days.

**Comment by mikah22** [comment]
Thanks for the quick reply. Yes you are right about the right icon, my bad I didn't look at the documentation close enough. Regarding headerBackgroundColorOpened, did you already check-in this code because I am unable to find it in the repo. Also while we are at this, can you also provide an option to change the content border color (because in my case content border color is the same color as the header) when the section is open (maybe name it as contentBorderColorOpened)

**Comment by GotJimmy** [comment]
No, haven't published yet.
Regarding contentBorderColorOpened: I think this is of no use since the content border is only visible when open. So there is no need to switch between 2 colors if only one is ever shown.

**Comment by GotJimmy** [comment]
2.2.0 has been published.
See changelog.md for details.
Enjoy!

**Comment by mikah22** [comment]
> No, haven't published yet. Regarding contentBorderColorOpened: I think this is of no use since the content border is only visible when open. So there is no need to switch between 2 colors if only one is ever shown.

Good Point.
