### ISSUE TITLE
The following assertion was thrown building Accordion(dirty): setState() or markNeedsBuild() called during build.

### ISSUE THREAD

**Issue by shahidpharm** [GotJimmy/accordion#14]
Hi, I am using the below code which has been copied from exmaple shared in this git but I faced problem

**Code:**

`import 'package:flutter/material.dart';

import 'package:get/get.dart';
import 'package:getwidget/getwidget.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:rupga_app/app/modules/finance/controllers/finance_controller.dart';
import 'package:rupga_app/screens/components/common_app_bar.dart';

import '../controllers/expenditure_controller.dart';
import 'package:accordion/accordion.dart';
import 'package:intl/intl.dart';

class ExpenditureView extends GetView<FinanceController> {
  final FinanceController _financeController = Get.put(FinanceController());

  final _headerStyle = const TextStyle(
      color: Color(0xffffffff), fontSize: 15, fontWeight: FontWeight.bold);
  final _contentStyleHeader = const TextStyle(
      color: Color(0xff999999), fontSize: 14, fontWeight: FontWeight.w700);
  final _contentStyle = const TextStyle(
      color: Color(0xff999999), fontSize: 14, fontWeight: FontWeight.normal);
  final _loremIpsum = 'Hello';
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: CommonAppBar('Expenditures'),
        body: Accordion(
            maxOpenSections: 1,
            headerPadding:
                const EdgeInsets.symmetric(vertical: 7, horizontal: 15),
            // sectionOpeningHapticFeedback: SectionHapticFeedback.heavy,
            // sectionClosingHapticFeedback: SectionHapticFeedback.light,
            // openAndCloseAnimation: false,
            children: [
              AccordionSection(
                isOpen: true,
                leftIcon:
                    const Icon(Icons.insights_rounded, color: Colors.white),
                headerBackgroundColor: Colors.black,
                header: Text('Introduction', style: _headerStyle),
                content: Text(_loremIpsum, style: _contentStyle),
                contentHorizontalPadding: 20,
                contentBorderWidth: 1,
                // sectionOpeningHapticFeedback: SectionHapticFeedback.heavy,
                // sectionClosingHapticFeedback: SectionHapticFeedback.vibrate,
              ),
              AccordionSection(
                isOpen: false,
                leftIcon:
                    const Icon(Icons.compare_rounded, color: Colors.white),
                header: Text('About Us', style: _headerStyle),
                contentBorderColor: const Color(0xffffffff),
                content: Row(
                  children: [
                    const Icon(Icons.compare_rounded,
                        size: 120, color: Colors.orangeAccent),
                    Flexible(
                        flex: 1,
                        child: Text(_loremIpsum, style: _contentStyle)),
                  ],
                ),
              ),
              AccordionSection(
                isOpen: false,
                leftIcon: const Icon(Icons.food_bank, color: Colors.white),
                header: Text('Company Info', style: _headerStyle),
                content: DataTable(
                  sortAscending: true,
                  sortColumnIndex: 1,
                  dataRowHeight: 40,
                  showBottomBorder: false,
                  columns: [
                    DataColumn(
                        label: Text('ID', style: _contentStyleHeader),
                        numeric: true),
                    DataColumn(
                        label: Text('Description', style: _contentStyleHeader)),
                    DataColumn(
                        label: Text('Price', style: _contentStyleHeader),
                        numeric: true),
                  ],
                  rows: [
                    DataRow(
                      cells: [
                        DataCell(Text('1',
                            style: _contentStyle, textAlign: TextAlign.right)),
                        DataCell(Text('Fancy Product', style: _contentStyle)),
                        DataCell(Text(r'$ 199.99',
                            style: _contentStyle, textAlign: TextAlign.right))
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('2',
                            style: _contentStyle, textAlign: TextAlign.right)),
                        DataCell(Text('Another Product', style: _contentStyle)),
                        DataCell(Text(r'$ 79.00',
                            style: _contentStyle, textAlign: TextAlign.right))
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3',
                            style: _contentStyle, textAlign: TextAlign.right)),
                        DataCell(
                            Text('Really Cool Stuff', style: _contentStyle)),
                        DataCell(Text(r'$ 9.99',
                            style: _contentStyle, textAlign: TextAlign.right))
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('4',
                            style: _contentStyle, textAlign: TextAlign.right)),
                        DataCell(Text('Last Product goes here',
                            style: _contentStyle)),
                        DataCell(Text(r'$ 19.99',
                            style: _contentStyle, textAlign: TextAlign.right))
                      ],
                    ),
                  ],
                ),
              ),
              AccordionSection(
                isOpen: false,
                leftIcon: const Icon(Icons.contact_page, color: Colors.white),
                header: Text('Contact', style: _headerStyle),
                content: Wrap(
                  children: List.generate(
                      30,
                      (index) => const Icon(Icons.contact_page,
                          size: 30, color: Color(0xff999999))),
                ),
              ),
              AccordionSection(
                isOpen: false,
                leftIcon: const Icon(Icons.computer, color: Colors.white),
                header: Text('Jobs', style: _headerStyle),
                content: const Icon(Icons.computer,
                    size: 200, color: Color(0xff999999)),
              ),
              AccordionSection(
                isOpen: false,
                leftIcon: const Icon(Icons.movie, color: Colors.white),
                header: Text('Culture', style: _headerStyle),
                content: const Icon(Icons.movie,
                    size: 200, color: Color(0xff999999)),
              ),
              AccordionSection(
                isOpen: false,
                leftIcon: const Icon(Icons.people, color: Colors.white),
                header: Text('Community', style: _headerStyle),
                content: const Icon(Icons.people,
                    size: 200, color: Color(0xff999999)),
              ),
            ]));
  }
}
`

**Problem:**
The following assertion was thrown building Accordion(dirty):
setState() or markNeedsBuild() called during build.

This Obx widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: Obx
  has builder
  state: _ObxState#bedb9
The widget which was currently being built when the offending call was made was: Accordion
  dirty
The relevant error-causing widget was: 
  Accordion Accordion:file:///F:/Info/devs/Flutter/getx/new%20app/rupga/From%20flutter%20way%20UI/rupga_app/lib/app/modules/expenditure/views/expenditure_view.dart:27:13
When the exception was thrown, this was the stack: 

![Screenshot_1645945104](https://user-images.githubusercontent.com/21261808/155872050-498c4031-fe81-4c67-8fcf-59382a322543.png)

Please help.
Thanks

**Comment by GotJimmy** [comment]
I used your code and it runs just fine on my machine. I can only guess that you're changing a Getx variable some other place while the Accordion is being built (in a constructor?). But based on the code you sent I cannot replicate the problem. See linked video:

https://user-images.githubusercontent.com/6039735/155899287-7bc6fc7d-dcc8-496b-b117-aacf3e0995bc.mov

**Comment by vinitbhamare** [comment]
@GotJimmy I am getting same error. Few observations:
1. First time AccordionScreen loads fine.
2. When you get to new screen using Get.to(() => AccordionScreen()) from first screen, the error occurs.
3. I think its preventing duplicates from Accordion screen, the controller might be singleton?

**Comment by vinitbhamare** [comment]
@GotJimmy Looks like this issue fixed in latest version 2.2.2 4 hours back! I was using 2.2.1 and you made available 2.2.2 to fix another issue which does solve this issue as well. 

Many Thanks!
Vinit
