### ISSUE TITLE
Accordion with PageView crash

### ISSUE THREAD

**Issue by delegate-it** [GotJimmy/accordion#15]
When I have a PageView that is calling page that implements Accordion, it always crashes on the second page while swiping. The error doesn't happen if I set maxOpenSections: 0 (which is useless). I think something to do with the animation.
This is my code
`
              Accordion(
                headerBorderRadius: 1.0,
                maxOpenSections: 1,
                paddingListHorizontal: 0,
                scrollIntoViewOfItems: ScrollIntoViewOfItems.slow,
                disableScrolling: true,
                rightIcon: Icon(Icons.arrow_drop_down),
                headerBackgroundColor: Colors.grey.withOpacity(0.6),
                headerBackgroundColorOpened: Color(0xFF0099FF),
                // headerPadding: EdgeInsets.all(10),
                children: [
                  AccordionSection(
                    contentBorderRadius: 1.0,
                    isOpen: true,
                    header: Center(
                      child: Text('MY DETAILS',
                          style: TextStyle(
                              color: Colors.white,
                              fontSize: 17,
                              fontWeight: FontWeight.bold)),
                    ),
                    content: MyDetailsWidget(
                      profile: widget.profile,
                      user: widget.user!,
                    ),
                  ),
                  AccordionSection(
                    contentBorderRadius: 1.0,
                    isOpen: false,
                    header: Center(
                      child: Text('SKILLZ DETAILS',
                          style: TextStyle(
                              color: Colors.white,
                              fontSize: 17,
                              fontWeight: FontWeight.bold)),
                    ),
                    content: SkillzDetailsWidget(
                      profile: widget.profile!,
                    ),
                  ),
                  AccordionSection(
                    isOpen: false,
                    header: Center(
                      child: Text('ADVERTISING',
                          style: TextStyle(
                              color: Colors.white,
                              fontSize: 17,
                              fontWeight: FontWeight.bold)),
                    ),
                    content: Advertising(
                      profile: widget.profile!,
                    ),
                  ),
                ],
              ),`

Below is the error generated
`#24     Element.inflateWidget
package:flutter/…/widgets/framework.dart:3874
#25     MultiChildRenderObjectElement.inflateWidget
package:flutter/…/widgets/framework.dart:6606
#26     MultiChildRenderObjectElement.mount
package:flutter/…/widgets/framework.dart:6618
...     Normal element mounting (83 frames)
#109    Element.inflateWidget
package:flutter/…/widgets/framework.dart:3874
#110    MultiChildRenderObjectElement.inflateWidget
package:flutter/…/widgets/framework.dart:6606
#111    MultiChildRenderObjectElement.mount
package:flutter/…/widgets/framework.dart:6618
...     Normal element mounting (125 frames)
#236    Element.inflateWidget
package:flutter/…/widgets/framework.dart:3874
#237    Element.updateChild
package:flutter/…/widgets/framework.dart:3617
#238    SliverMultiBoxAdaptorElement.updateChild
package:flutter/…/widgets/sliver.dart:1243
#239    SliverMultiBoxAdaptorElement.createChild.<anonymous closure>
package:flutter/…/widgets/sliver.dart:1228
#240    BuildOwner.buildScope
package:flutter/…/widgets/framework.dart:2628
#241    SliverMultiBoxAdaptorElement.createChild
package:flutter/…/widgets/sliver.dart:1221
#242    RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure>
package:flutter/…/rendering/sliver_multi_box_adaptor.dart:349
#243    RenderObject.invokeLayoutCallback.<anonymous closure>
package:flutter/…/rendering/object.dart:1997
#244    PipelineOwner._enableMutationsToDirtySubtrees
package:flutter/…/rendering/object.dart:918
#245    RenderObject.invokeLayoutCallback
package:flutter/…/rendering/object.dart:1997
#246    RenderSliverMultiBoxAdaptor._createOrObtainChild
package:flutter/…/rendering/sliver_multi_box_adaptor.dart:338
#247    RenderSliverMultiBoxAdaptor.insertAndLayoutChild
package:flutter/…/rendering/sliver_multi_box_adaptor.dart:484
#248    RenderSliverFixedExtentBoxAdaptor.performLayout
package:flutter/…/rendering/sliver_fixed_extent_list.dart:250
#249    RenderObject.layout
package:flutter/…/rendering/object.dart:1887
#250    RenderSliverEdgeInsetsPadding.performLayout
package:flutter/…/rendering/sliver_padding.dart:137
#251    _RenderSliverFractionalPadding.performLayout
package:flutter/…/widgets/sliver_fill.dart:167
#252    RenderObject.layout
package:flutter/…/rendering/object.dart:1887
#253    RenderViewportBase.layoutChildSequence
package:flutter/…/rendering/viewport.dart:510
#254    RenderViewport._attemptLayout
package:flutter/…/rendering/viewport.dart:1580
#255    RenderViewport.performLayout
package:flutter/…/rendering/viewport.dart:1489
#256    RenderObject._layoutWithoutResize
package:flutter/…/rendering/object.dart:1731
#257    PipelineOwner.flushLayout
package:flutter/…/rendering/object.dart:887
#258    RendererBinding.drawFrame
package:flutter/…/rendering/binding.dart:497
#259    WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:883
#260    RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:363
#261    SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1144
#262    SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1081
#263    SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:995
#267    _invoke (dart:ui[/hooks.dart:151:10]())
#268    PlatformDispatcher._drawFrame (dart:ui[/platform_dispatcher.dart:308:5]())
#269    _drawFrame (dart:ui[/hooks.dart:115:31]())
(elided 3 frames from dart:async)`

**Comment by delegate-it** [comment]
Hi @GotJimmy, thank you for your prompt response. Greatly appreciate it.

 I managed to avoid the error by making all the AccordionSection isOpen = false. Below are the 2 files with the pageview.

[Archive.zip](https://github.com/GotJimmy/accordion/files/8198624/Archive.zip)

**Comment by GotJimmy** [comment]
Ok, thanks. I'll have a look at it.

**Comment by GotJimmy** [comment]
Thanks for the code. However, you're using lots of custom widgets in that and I get 50+ errors because I don't have those widgets. Can you send me a working example that I can work with. Would be good if you could use the example project included in the Accordion package to start with that replicates the error.

**Comment by GotJimmy** [comment]
I have a look soon.

**Comment by GotJimmy** [comment]
I can see the problem. Checking what I can do to fix it.

**Comment by GotJimmy** [comment]
Quick fix for right now would be to set maxOpenSections to anything you like, but to set each AccordionSection.isOpen to false. That works for me here. Can you confirm?

**Comment by delegate-it** [comment]
> Quick fix for right now would be to set maxOpenSections to anything you like, but to set each AccordionSection.isOpen to false. That works for me here. Can you confirm?

Yes I confirm that.

**Comment by GotJimmy** [comment]
I'm on it. But it will probably take a bit longer.

**Comment by GotJimmy** [comment]
I just published Accordion v2.2.2 with fixes for your problem. Can you take a look if this helps?
