### ISSUE TITLE
Can you tell me how to contorl each accordionsection in below source code

### ISSUE THREAD

**Issue by Gaebal2** [GotJimmy/accordion#16]
First of all, thank you for great widget.

Error code :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
Reloaded 8 of 884 libraries in 567ms.
E/flutter (10307): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 108 pos 12: '_positions.length == 1': ScrollController attached to multiple scroll views.
10307): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (10307): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (10307): #2      ScrollController.position
package:flutter/…/widgets/scroll_controller.dart:108
E/flutter (10307): #3      AutoScrollControllerMixin._bringIntoViewportIfNeed
package:scroll_to_index/scroll_to_index.dart:417
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Below is my source code. Can you tell me how to handle each AccordionSection in this case?
I want  to create Cardlist for each persons data from firestore database and I want to attach chat window using Accordion widget.
but don't know how to control each Accordionsection in this case. 
I mean I want to control each Accordionsection as if I added many children Accordionsection in Accorion widget.

class CardlistScreen extends StatelessWidget {
  const CardlistScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Expanded(
          child: StreamBuilder(
            stream:
                FirebaseFirestore.instance.collection('cardlist').snapshots(),
            builder: (context,
                AsyncSnapshot<QuerySnapshot<Map<String, dynamic>>> snapshot) {
              if (snapshot.connectionState == ConnectionState.waiting) {
                return Center();
              }
              final chatDocsListData = snapshot.data!.docs;
              return ListView.builder(
                itemCount: chatDocsListData.length,
                itemBuilder: (context, index) => Card(
                  child: Container(
                    padding: EdgeInsets.all(10),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          mainAxisAlignment: MainAxisAlignment.start,
                          children: [
                            CircleAvatar(
                              child: Icon(Icons.person),
                              radius: 30,
                            ),
                            SizedBox(
                              width: 10,
                            ),
                            Text(
                              chatDocsListData[index]['userEmailAddress'],
                              style: TextStyle(fontWeight: FontWeight.bold),
                            ),
                          ],
                        ),
                        SizedBox(
                          height: 10,
                        ),
                        Accordion(
                          paddingListHorizontal: 0,
                          headerBorderRadius: 5,
                          paddingListTop: 0,
                          paddingListBottom: 0,
                          headerBackgroundColorOpened: Colors.black54,
                          headerPadding:
                              EdgeInsets.symmetric(vertical: 7, horizontal: 15),
                          children: [
                            AccordionSection(
                              isOpen: false,
                              leftIcon: Icon(Icons.chat, color: Colors.white),
                              header: Text(
                                'Chat',
                              ),
                              content: Column(
                                children: [
                                  Container(
                                    width: MediaQuery.of(context).size.width,
                                    height: 250,
                                    child: Text(
                                      'ChatScreen',
                                    ),
                                  ),
                                  Container(
                                    height: 50,
                                    child: Text(
                                      'ChatTypeInTextField',
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ),
              );
            },
          ),
        ),
        SizedBox(
          height: 30,
        ),
      ],
    );
  }
}

**Comment by GotJimmy** [comment]
I guess you want to dynamically create `AccordionSections` from what comes back from Firebase??
In that case you would take your list of data and dynamically map sections ...

```
        child: Accordion(children: myCollection.map((item) => AccordionSection(
					isOpen: item.open,
					header: Text(item.header), 
					content: Text(item.content),
				)))
```

**Comment by Gaebal2** [comment]
> I guess you want to dynamically create `AccordionSections` from what comes back from Firebase?? In that case you would take your list of data and dynamically map sections ...
> 
> ```
>         child: Accordion(children: myCollection.map((item) => AccordionSection(
> 					isOpen: item.open,
> 					header: Text(item.header), 
> 					content: Text(item.content),
> 				)))
> ```

**Comment by Gaebal2** [comment]
Thank you for your quick response but could you please be more specific on explanation with some example code. Sorry I'm newbe in this development area.

**Comment by Gaebal2** [comment]
Let me put it simple way.
In below code how to open and close AccordionSection while the other doesn't open and close simultaneously.

  Accordion(
              headerBackgroundColorOpened: Colors.black54,
              children: [
                AccordionSection(
                  isOpen: false,
                  header: Text('Introduction', style: _headerStyle),
                  content: Text(_loremIpsum, style: _contentStyle),
                ),
              ],
            ),
            Accordion(
              headerBackgroundColorOpened: Colors.black54,
              children: [
                AccordionSection(
                  header: Text('Introduction', style: _headerStyle),
                  content: Text(_loremIpsum, style: _contentStyle),
                ),
              ],
            ),
