### ISSUE TITLE
Callback on opening and closing of AccordionSection

### ISSUE THREAD

**Issue by singh-karan-7** [GotJimmy/accordion#17]
This library should add a callback whenever user taps on the header of a AccordionSection. This can help us get the current opened Section and we can make some other function calls or UI changes.
If there is any current way of doing this, then, please, do reply.

Thanks!!!

**Comment by GotJimmy** [comment]
Sounds like a good idea. I'll add this functionality in the next version soon.

**Comment by ahaneef29** [comment]
@singh-karan-7 This is what I'm looking for it.. @GotJimmy ?

**Comment by GotJimmy** [comment]
@singh-karan-7 This PR (including some improvements) will be published tonight. Sorry for the late reply!
