### ISSUE TITLE
setState closes accordion

### ISSUE THREAD

**Issue by cremfert** [GotJimmy/accordion#21]
I'm using the library on a Flutter desktop project and everything is working fine, except one thing:
if an accordion section is open and somewhere else in the widget a setState is called, the accordion closes. How can I prevent this?

Thanks a lot!

**Comment by GotJimmy** [comment]
Shouldn't be but hard to say without an example. Is the section `isOpen` parameter controlled by setState in your app? Do you have a minimalistic example you could send me?
