### ISSUE TITLE
RangeError with an accordion with more than 1000 AccordionSection

### ISSUE THREAD

**Issue by thorizer** [GotJimmy/accordion#24]
Exception has occurred.
RangeError (RangeError (index): Invalid value: Not in inclusive range 0..999: 1000)
I tried to wrap all AccordionSections in a ListView.builder but it didn't work

**Comment by GotJimmy** [comment]
Yeah, 1000 is a hard limit right now. How many do you need?

**Comment by thorizer** [comment]
1500, the better option is to support listview builder as a container somehow. 
accordion helps with large amounts of data to show only a preview. 
listview builder is good performance wise but you still need to scroll the whole data set to reach the bottom

**Comment by GotJimmy** [comment]
The limit of `AccordionSections` is now 10,000.
