### ISSUE TITLE
Accordion section close with warning 

### ISSUE THREAD

**Issue by ziadikheira** [GotJimmy/accordion#27]
I have accordion sections with text fields, and when i try to open it , it's close with this warning:
[GETX] Instance "ListController" has been created with tag "440431361"
[GETX] Instance "ListController" with tag "440431361" has been initialized

**Comment by GotJimmy** [comment]
You have the `AccordionSection` wrapped by an `Accordion`, right? An example would help as I cannot do much with the warnings above.
