### ISSUE TITLE
Not working well with the Refresh Indicator

### ISSUE THREAD

**Issue by AlpSha** [GotJimmy/accordion#3]
Requires a parameter as `physics: AlwaysScrollableScrollPhysics()` in order to be scrollable when list is not covering the whole page as mentioned on this issue:
https://stackoverflow.com/a/57520024/11088485

**Comment by GotJimmy** [comment]
I will look into this this week.

**Comment by GotJimmy** [comment]
shrinkWrap and AlwaysScrollableScrollPhysics() has been added.
