### ISSUE TITLE
Color transparent 

### ISSUE THREAD

**Issue by AndriiReverchuk** [GotJimmy/accordion#32]
When I use transparent content background color, the background color is still white.

**Comment by GotJimmy** [comment]
I think the content background shouldn't be transparent, otherwise the background and the content's content get all mixed up. So white is the base color of the content and on top of that you can use any content color you want.

**Comment by BenevidesLecontes** [comment]
Hi @GotJimmy thanks for your amazing library, using Color transparent on content is useful on cases where we don't have solid color as background. Ex: Images or gradients.

**Comment by GotJimmy** [comment]
Thanks! Alright, I'll have another look at transparent background of a section.
