### ISSUE TITLE
Don't animate opening on first page load

### ISSUE THREAD

**Issue by j4m3s** [GotJimmy/accordion#33]
I'm using Bloc to manage state.

In our app, a user might open an accordion section and enter a value into one of several inputs in that section. Doing so writes to the Bloc, and causes a rebuild of the page.

When the page is rebuilt we want that same section to remain open, in case the user wants to make a further change, so we set isOpen to true. 

However, when the page reloads it animates the section opening.

How should we suppress that animation just for the isOpen section so that the user isn't interrupted? Should we set the whole Accordion not to animate by default and the enable animation on the first onOpen or onClose event maybe?  I think that would be a useful "built int" feature, that you could choose whether or not that initial rendering includes animation or not. But happy to handle it in our code rather than yours if you disagree :)

**Comment by GotJimmy** [comment]
Basically, the Accordion widget is meant to be built once and then just reacting to state (like opening/closing one section). If you rebuild the entire Accordion then the opening animation is played each time unless you disable that animation. You could however keep in your state one bool variable (i.e. isFirstBuild) that changes to false after the first build and then use this state variable to disable the opening animation on the second build. You could also use this setting as a static variable if you prefer.

**Comment by j4m3s** [comment]
Understood, thank you for the prompt reply.

**Comment by j4m3s** [comment]
Actually I've just realised that the issue isn't the animation itself, it's that there seems to be a delay between rendering the accordion and then opening the section marked with isOpen. That appears to be deliberate looking at accordion_section.dart:120 - the opening is delayed using a timer. Is my understanding correct, and if so what is the thinking behind that delay
 (especially if the animation is disabled...).

**Comment by GotJimmy** [comment]
The delay is good for the following situation: you navigate to a new page (which takes a certain amount of milliseconds), then once this animation is finished the accordion plays its animation. Basically to keep the two animations separate from each other.

**Comment by j4m3s** [comment]
Yes I see what you mean.  Would you consider making it configurable/ optional, for those of us using bloc to manage state?  In our case it would be preferable to simply have any `isOpen` items rendered open, rather than initially rendering them closed and then opening them.  I suspect that might be a useful option for others too?

**Comment by GotJimmy** [comment]
I don't see how bloc would require any difference in this widget. Try playing around with `sectionAnimation` and `sectionScaleAnimation` and see if this solves your problem.

**Comment by j4m3s** [comment]
Unfortunately, changing `sectionAnimation` and/or `sectionScaleAnimation` don't avoid the opening delay.  It just means that the section opens _after the delay here_ https://github.com/GotJimmy/accordion/tree/master/lib/accordion_section.dart#L125-L127 without animating.  It doesn't mean that it's rendered open.

**Comment by GotJimmy** [comment]
Ok, I'll try to have a look at it this week.

**Comment by HubnerJonathan** [comment]
Hello,

I have the same problem and can't find a fix. Would you be so kind to tell me what to do ?

BR.

**Comment by GotJimmy** [comment]
I'll address this problem and others in a new major version later this year.
