### ISSUE TITLE
GetX Instance "ListController"  block app

### ISSUE THREAD

**Issue by vladox1975** [GotJimmy/accordion#34]
Hi,

In the debugging console it tells me that a large number of ListController instances are being created. That ends up crashing my interface and disconnecting debugging.

![imagen](https://user-images.githubusercontent.com/88164514/202751031-29b0c1b3-6886-46ee-922f-07105f33add7.png)

**Comment by vladox1975** [comment]
![imagen](https://user-images.githubusercontent.com/88164514/202751537-3babf404-518c-405a-a358-05de88262b71.png)

**Comment by vladox1975** [comment]
![imagen](https://user-images.githubusercontent.com/88164514/202751862-0331bb00-d73a-4282-bc89-359912193b09.png)

**Comment by vladox1975** [comment]
I run the clean command and pub get; but still the problem.

**Comment by GotJimmy** [comment]
Can you send me the code with the Accordion (and all accordion sections) so I can have a look?

**Comment by vladox1975** [comment]
Hi,

import 'package:accordion/accordion.dart';
import 'package:flutter/material.dart';
import 'dart:convert';
import 'package:http/http.dart' as http;

Other imports....



class Ayuda extends StatefulWidget {
  @override
  _AyudaState createState() => _AyudaState();
}

class _AyudaState extends State<Ayuda> {
  _AyudaState() {

  }

  List listaCertificados = [];
  List<AccordionSection> widgetsCertificados = [];
  Future recibirCertificados() async {
    listaCertificados.clear();
    try {
      var url = Uri.parse( ); //an API
      final respuesta = await http.get(url);
      if (respuesta.statusCode == 200) {
        setState(() {
          var parsedJson = json.decode(respuesta.body);
          if (parsedJson["success"]) {
            for (final itemLote in parsedJson["resultado"])
              listaCertificados.add(new Ayudas.fromJson(itemLote));
          }
          int cont = 1;
          for (final item in listaCertificados) {
            YoutubePlayerController _controller = YoutubePlayerController(
              initialVideoId: item.video.toString(),
              flags: YoutubePlayerFlags(
                  autoPlay: false,
                  mute: false,
                  loop: true,
                  hideThumbnail: true,
                  controlsVisibleAtStart: false),
            );

            widgetsCertificados.add(
           **AccordionSection(**
              leftIcon: Icon(
                Icons.help_rounded,
                color: Colors.white,
              ),
              isOpen: false,
              headerBackgroundColor:
                  cont.isOdd ? Colors.blue : Color.fromRGBO(22, 101, 180, 1),
              header: Text(item.descripcion,
                  style: TextStyle(color: Colors.white, fontSize: 17)),
              content: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Container(
                    child: Text(item.detalle),
                  ),
                  Container(
                    margin: EdgeInsets.fromLTRB(0, 15, 0, 0),
                    child: YoutubePlayer(
                      controller: _controller,
                      liveUIColor: Colors.amber,
                    ),
                  )
                ],
              ),
            ));
            cont += 1;
          }
        });
      }
    } catch (e) {

    }
  }

  @override
  void initState() {
    if (mounted) {
      // setState(() =>
      recibirCertificados();
      //  );
      super.initState();
    }
  }

  @override
  Widget build(BuildContext context) {
    Responsive responsive = new Responsive(context);
    return new WillPopScope(
      onWillPop: () async {
        Navigator.of(context).pop();
        return false;
      },
      child: new Scaffold(
        appBar: new AppBar(
          toolbarHeight: responsive.dp(14),
          leading: new IconButton(
              icon: new Icon(
                Icons.arrow_back_rounded,
                size: 35.0,
              ),
              onPressed: () {
                Navigator.of(context).pop();
              }),
          backgroundColor: Color.fromRGBO(22, 101, 180, 1),
          flexibleSpace: FlexibleSpaceBar(
            centerTitle: true,
            title: BannerSuperior(
              nombre: Users.objUser.nombre == '' ? null : Users.objUser.nombre,
              porcTopLogo: 0,
              porcBottomLogo: 1,
              porcTopLogin: 4,
              porcBottomLogin: 0,
              tipoOro: false,
              tipoInsumo: false,
            ),
          ),
        ),
        body: SafeArea(
          child: Container(
            margin: EdgeInsets.fromLTRB(0, 15, 0, 0),
            child: Accordion(
              maxOpenSections: 1,
              children: widgetsCertificados,
            ),
          ),
        ),
      ),
    );
  }
}

**Comment by GotJimmy** [comment]
Hard to say without all the imports. But you seem to create a list of AccordionSection separately ... have you tried moving the creation of those sections directly into the Accordion? Just a guess.
Another idea would be to use the included example app and base your app on that by changing it.
Getting the debug message from GetX is normal (see example app) and not an error itself.
