### ISSUE TITLE
setState issue in accordion

### ISSUE THREAD

**Issue by RushikeshB97** [GotJimmy/accordion#36]
Hello,

Thanks for this amazing package.

I have accordion, inside accordion there I have 2 sections.
Each section has one dropdown, when user selects dropdown value, I need to set the same value for other accordion dropdown.

Now when I try to do setState after selecting value, accordion closes on its own.

Is there a way, I can use setstate without affecting accordion state?

Thanks!

**Comment by GotJimmy** [comment]
The dropdown of yours is in the content section of `AccordionSection`, not in the header, right? What have you set for `maxOpenSections` in `Accordion`?

**Comment by RushikeshB97** [comment]
Hello,

Thanks for reply.

Yes, dropdown is in content section.

Hierarchy is like this : content -> column -> accordion -> accordion sections.

I managed to solve it at most extent by adding following flags:

maxOpenSections: 10,
openAndCloseAnimation: false,
scaleWhenAnimating: false

Feel free to close this thread.

Thanks!

**Comment by GotJimmy** [comment]
Glad it worked out for you!
