### ISSUE TITLE
Endlessly recreated

### ISSUE THREAD

**Issue by eg-97kr** [GotJimmy/accordion#39]
The stack in which the card lies is used. Scooter markers on the map. If you click on the marker, the scooter card opens. And in it, using Accordion, I want to choose a tariff, payment method, and so on. But the problem is that when I open the scooter card, the Accordion goes into a beckoning re-creation. The following is endlessly written in the console
[GETX] Instance "ListController" has been created with tag "[number]"
[GETX] Instance "ListController" with tag "[number]" has been initialized
Why the AccordionSection cannot be interacted with

Thanks a lot for your attention

**Comment by GotJimmy** [comment]
The AccordionSection can be interacted with!
Have you checked your code if you're recreating the sections (i.e. via state)? Because getting the GETX messages indicates that they're created over and over again.

**Comment by eg-97kr** [comment]
I apologize
The case really was able. I realized that they are created again and again. My colleague elsewhere added a setState that I didn't see right away. This created the problem

Thank you very much for the quick response and for your attention to my question!

**Comment by GotJimmy** [comment]
You're welcome and I'm glad this worked out for you!
