### ISSUE TITLE
Marging and Padding adjust

### ISSUE THREAD

**Issue by Potorato** [GotJimmy/accordion#44]
Hello. Is it possible to adjust the margin of the accordion as well as the margins of the sections? The idea is for them to occupy the full width of the screen. Thank you.

**Comment by GotJimmy** [comment]
Yes, see `paddingListHorizontal`. You may also want to adjust `headerBorderRadius` when going full width.

**Comment by Potorato** [comment]
Thanks for the reply! I'm going to try it

**Comment by Potorato** [comment]
> Yes, see `paddingListHorizontal`. You may also want to adjust `headerBorderRadius` when going full width.

Tried. Perfect. Thanks for the help
