### ISSUE TITLE
Make flip rotation counter customisable parameter

### ISSUE THREAD

**Issue by anatoliisudor** [GotJimmy/accordion#45]
First of all, thanks for such an excellent library.
Customizing flippable behavior for the accordion section right icon with a basic boolean flag is possible.
And you are using RotatedBox for the right icon component, which supports not only flip by setting _flipQuarterTurns to 2 but also rotation to 90 degrees by providing 1.
```dart
  /// getter to flip the widget vertically (Icon by default)
  /// on the right of this section header to visually indicate
  /// if this section is open or closed
  get _flipQuarterTurns =>
      flipRightIconIfOpen?.value == true ? (_isOpen ? 2 : 0) : 0;
``` 
It would be nice to have a possibility to set this value in options. What do you think?
Here are the images describing what it can look like if we rotate the right icon by 90 degrees:
- Closed: [https://share.getcloudapp.com/ApugA5Ye](https://share.getcloudapp.com/ApugA5Ye)
- Open: [https://share.getcloudapp.com/p9uZPWb7](https://share.getcloudapp.com/p9uZPWb7)

**Comment by GotJimmy** [comment]
Thanks.
While it's true that you `flipRightIconIfOpen` only supports open or closed, you could use the `rightIcon` parameter to send in your own widget and turn and customize it whichever way you like.

**Comment by Daybayzayd** [comment]
Hello,

I'm facing the same problem. Maybe i'm a newbie, but i want a rotation of 90 on the left icon. Unfortunately, the rotation is 180 actually, and we can't parameter that.

Unfortunately, in accordionsection, we can't access to "isOpen" value to dynamically change the icon orientation.

How can we achieve this without a lot of code ?

Thanks.
