### ISSUE TITLE
contentBackgroundColor transparent

### ISSUE THREAD

**Issue by yogithesymbian** [GotJimmy/accordion#5]
can i change the content background colour to transparent ?

i have tried with this code
```
contentBackgroundColor: Colors.transparent,,
```

and the background didnt change into transparent.

**Comment by GotJimmy** [comment]
I don't think so but I'll have to fix a few things this week anyway and then I can tell you for sure.

**Comment by GotJimmy** [comment]
Sorry for the delay. Ok, transparent background color is not an option at this point. Can you change the background and border color of the content to the same color as your app?
