### ISSUE TITLE
Accordion section content container has a hard coded white background

### ISSUE THREAD

**Issue by jonsamwell** [GotJimmy/accordion#51]
This is problematic in dark mode as the accordion section content background is always white.

https://github.com/GotJimmy/accordion/blob/master/lib/accordion_section.dart#L271

Could this be made configurable?

**Comment by GotJimmy** [comment]
Have you tried setting `contentBackgroundColor` to your color?

**Comment by anilflutter** [comment]
can make content background color is transparent? and can show content separate to header.

**Comment by GotJimmy** [comment]
Transparent is not going to work I think. How about using the same color for the content background as the background outside the Accordion?

**Comment by jonsamwell** [comment]
@GotJimmy I've set the content background colour to transparent with no effect. I think it is that hard-coded white value.

**Comment by jonsamwell** [comment]
None of the colours seems to work when in dark mode as the content and header backgrounds take on the white colour

Dark Mode:

![image](https://github.com/GotJimmy/accordion/assets/3694497/1faa1f4d-8f9e-4425-80ed-f515054ba0a5)

Light Mode: 

![image](https://github.com/GotJimmy/accordion/assets/3694497/6106f9ff-c364-4dc1-8401-41cfae0039eb)

Code: 

```
Accordion(
            disableScrolling: true,
            paddingListTop: 0,
            paddingListHorizontal: 0,
            contentBackgroundColor: Colors.transparent,
            contentBorderColor: Colors.transparent,
            headerBackgroundColor: Colors.red,
            headerBackgroundColorOpened: Colors.transparent,
            contentBorderRadius: 0,
            contentBorderWidth: 0,
            contentHorizontalPadding: 0,
            contentVerticalPadding: 0,
            headerBorderRadius: 0,
            headerPadding: const EdgeInsets.only(top: 16),
            scaleWhenAnimating: false,
            rightIcon: const Opacity(
              opacity: .6,
              child: PlatformAdaptiveIcon(
                cupertinoIcon: CupertinoIcons.chevron_up_chevron_down,
                materialIcon: CupertinoIcons.chevron_up_chevron_down,
                iconSize: 20,
              ),
            ),
            children: [
              for (var subSpecialtySegment in goalSet.goals)
                AccordionSection(
                  isOpen: true,
                  header: Row(
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Padding(
                        padding: const EdgeInsets.only(right: 8),
                        child: Text(
                          subSpecialtySegment.subSpecialtyName,
                          style: TextStyle(
                            fontSize: 16,
                            color: context.isIos
                                ? CupertinoColors.label.resolveFrom(context)
                                : Theme.of(context).textTheme.labelLarge!.color,
                          ),
                        ),
                      ),
                      Text(
                        '(${subSpecialtySegment.completedCount.toString()}/${subSpecialtySegment.goals.length})',
                        style: TextStyle(
                          fontSize: 16,
                          color: (context.isIos
                                  ? CupertinoColors.label.resolveFrom(context)
                                  : Theme.of(context)
                                      .textTheme
                                      .labelLarge!
                                      .color!)
                              .withOpacity(0.6),
                        ),
                      ),
                    ],
                  ),
                  content: GoalSubSpecialty(
                    subSpecialtySegment: subSpecialtySegment,
                  ),
                  contentHorizontalPadding: 0,
                  contentBackgroundColor: Colors.transparent,
                  headerBackgroundColor: Colors.transparent,
                  contentBorderColor: Colors.transparent,
                  headerBackgroundColorOpened: Colors.transparent,
                )
            ],
          ),
```

**Comment by GotJimmy** [comment]
Oh that background! I thought you were referring to the background of a section. I'll take another look at your issue and fix it this week.

**Comment by GotJimmy** [comment]
Ok, I took a closer look at your problem using your code (your `Accordion` with `AccordionSections` from my example). No white background ... you cannot even set the background in the `Accordion`. The `contentBackgroundColor` you were referring to is actually for the background color of each `AccordionSection` and that you can change as you can see in the screenshot. 
The dark grey background around the list of sections comes in this case from a standard `Scaffold.backgroundColor` and I tried a few different colors:
<img width="449" alt="Screenshot 2023-08-20 at 16 34 55" src="https://github.com/GotJimmy/accordion/assets/6039735/7de7f932-de59-479f-ae18-0f7595a8a91f">

**Comment by GotJimmy** [comment]
Please try and confirm so that I can close this issue.
