### ISSUE TITLE
Content background doesn't support transparent background

### ISSUE THREAD

**Issue by sameer1612** [GotJimmy/accordion#55]
With transparent color mentioned:

<img width="625" alt="image" src="https://github.com/GotJimmy/accordion/assets/39580073/43ede8c2-7ace-467b-af7b-27cfe1efb969">
<img width="365" alt="image" src="https://github.com/GotJimmy/accordion/assets/39580073/d819e911-db0c-4a7f-a527-72309d2d821b">

Works with any other color:

<img width="711" alt="image" src="https://github.com/GotJimmy/accordion/assets/39580073/00886da5-07ec-4833-80de-b2ed7745b8d6">
<img width="377" alt="image" src="https://github.com/GotJimmy/accordion/assets/39580073/8a4edffd-f1a0-45a5-be05-6c7e08532b00">

**Comment by GotJimmy** [comment]
Right. Have you tried setting the content background to the same color as your app's background?

**Comment by sameer1612** [comment]
> Right. Have you tried setting the content background to the same color as your app's background?

Yeh. Gave a shot. Unfortunately this won't work because the background is not static. It's a gradient and the section this widget covers can't be made precisely the section of background gradient it overlaps with.

**Comment by GotJimmy** [comment]
This will work: set the following parameters for the section:

`contentBackgroundColor: Colors.transparent`
`contentBorderColor: Colors.transparent`
