### ISSUE TITLE
Getx debug messages flood my screen

### ISSUE THREAD

**Issue by ramanraja** [GotJimmy/accordion#60]
I see a lot of debug messages like the following on my VSCode console:
```
[GETX] Instance "ListController" has been created with tag "651991823"
[GETX] Instance "ListController" has been created with tag "404259980"
[GETX] Instance "ListController" with tag "404259980" has been initialized
[GETX] Instance "ListController" has been created with tag "111673543"
[GETX] Instance "ListController" with tag "111673543" has been initialized
[GETX] Instance "ListController" has been created with tag "850311170"
[GETX] Instance "ListController" with tag "850311170" has been initialized
[GETX] Instance "ListController" has been created with tag "876198043"
```
My project does not use GetX library. It has been included only as a dependency for Accordion.
How to turn off these messages?

**Comment by GotJimmy** [comment]
I will minimize those messages in the next update.

In the meantime you can filter your debug messages yourself:
   - in VSCode in the Debug Console window enter `!Instance` in the filter text input field on top
   - other editors also allow that but I don't know how

**Comment by ramanraja** [comment]
Sure, thanks.

**Comment by asmaalagzouli96** [comment]
Hi, was there ever a solution to that? 
same probleme

**Comment by GotJimmy** [comment]
The solution is in the response.
