### ISSUE TITLE
How to add label to header when header is not null

### ISSUE THREAD

**Issue by benedict1986** [GotJimmy/accordion#64]
Hi, thank you for building such great library. I would like to use it in my personal project. I would like to ask if there is any way to add a label similar as TextField so that when here is a widget in header in AccordionSection, I could have a label on the border of the header similar as when we type some text in TextField. Thank you

![image](https://github.com/GotJimmy/accordion/assets/7417859/97d353ed-ec1b-4924-9f73-e958d7a408b4)

**Comment by GotJimmy** [comment]
You're welcome!
You can add any widget in the header you want:
`
AccordionSection(
  header: TextField()
)
`

**Comment by benedict1986** [comment]
Thank you @GotJimmy , that's very helpful. I missed it.
