### ISSUE TITLE
Accordion closes when typing in a textbox within an accordion section

### ISSUE THREAD

**Issue by NTass02** [GotJimmy/accordion#69]
Every time I type in a text box that is within the content of an accordion section, the accordion closes. I'm able to focus to a textbox without the accordion closing, but once I type, the accordion closes. Each keyboard press is as if I'm pressing the accordion.

**Comment by GotJimmy** [comment]
This topic has been discussed several times -- please see closed issues and the included example app.

**Comment by NTass02** [comment]
> This topic has been discussed several times -- please see closed issues and the included example app.

Can you point me to

**Comment by NTass02** [comment]
I have things above the accordion and below the accordion that require state. How can I handle this? Do you have an example of including stateful content within an accordion?

**Comment by NTass02** [comment]
I figured it out. Mine was a complicated setup. It is quite messy, but I was able to get it to work. Thanks.
