### ISSUE TITLE
Disable internal scrolling

### ISSUE THREAD

**Issue by PalMit2002** [GotJimmy/accordion#7]
The accordian widget has an internal scroll view and there is no option to disable. This creates a problem when the parent widget is scrollable and the accordion itself is also scrollable.

**Comment by ampraveeen** [comment]
having same issue.

**Comment by GotJimmy** [comment]
I'll try to look into it over the weekend.

**Comment by GotJimmy** [comment]
I have added `disableScrolling` prop to `Accordion`.
