### ISSUE TITLE
Not Working with TextFormField

### ISSUE THREAD

**Issue by tenesh13** [GotJimmy/accordion#8]
in the content of the accordion section, I need TextFormField but in execution when I touch the textField to type something it closes the accordion sections (something like refresh the page) and I can't type anything

**Comment by GotJimmy** [comment]
I'm just writing the exact same thing (TextFormField in AccordionSection) and it's working normally. Can you supply the code of the entire Accordion widget so I can take a look? What device are you running on?

**Comment by tenesh13** [comment]
AccordionSection(
                  isOpen: false,
                  leftIcon: Icon(Icons.tag, color: Colors.black),
                  header: Text('Details', style: accordionHeaderStyle),
                  content:
                  TextFormField(
                    autofocus: false,
                    cursorColor: Get.isDarkMode?Colors.grey[100]:Colors.grey[700],
                    controller: _emailController,
                    style: subTitleStyle,
                    decoration: InputDecoration(
                      hintText: "Enter Your Email",
                      hintStyle: subTitleStyle,
                      focusedBorder: UnderlineInputBorder(
                          borderSide: BorderSide(
                              color: context.theme.backgroundColor,
                              width: 0
                          )
                      ),
                      enabledBorder: UnderlineInputBorder(
                          borderSide: BorderSide(
                              color: context.theme.backgroundColor,
                              width: 0
                          )
                      ),
                    ),
                  )
                ),

// I'm running on android device

**Comment by GotJimmy** [comment]
Sorry, I was busy. I'll look into it today. Can you reproduce this behavior in an Android emulator or does it only happen on a physical device?

**Comment by tenesh13** [comment]
No problem. It's happened on both Android emulator and physical device.

**Comment by GotJimmy** [comment]
Just tried your code (without the styling and emailController) and it seems to work just fine on an Android emulator:

`    AccordionSection(
            isOpen: false,
            leftIcon: Icon(Icons.tag, color: Colors.black),
            header: Text('Details'),
            content: TextFormField(
              autofocus: false,
              cursorColor: Get.isDarkMode ? Colors.grey[100] : Colors.grey[700],
              // controller: _emailController,
              // style: subTitleStyle,
              decoration: InputDecoration(
                hintText: 'Enter Your Email',
                // hintStyle: subTitleStyle,
                focusedBorder: UnderlineInputBorder(borderSide: BorderSide(color: context.theme.backgroundColor, width: 0)),
                enabledBorder: UnderlineInputBorder(borderSide: BorderSide(color: context.theme.backgroundColor, width: 0)),
              ),
            )),

https://user-images.githubusercontent.com/6039735/146401614-6abc0e28-81c9-4952-95c8-92516af285b1.mov

`

**Comment by GotJimmy** [comment]
Just tried your code (without the styling and emailController) and it seems to work just fine on an Android emulator:

` AccordionSection(
isOpen: false,
leftIcon: Icon(Icons.tag, color: Colors.black),
header: Text('Details'),
content: TextFormField(
autofocus: false,
cursorColor: Get.isDarkMode ? Colors.grey[100] : Colors.grey[700],
// controller: _emailController,
// style: subTitleStyle,
decoration: InputDecoration(
hintText: 'Enter Your Email',
// hintStyle: subTitleStyle,
focusedBorder: UnderlineInputBorder(borderSide: BorderSide(color: context.theme.backgroundColor, width: 0)),
enabledBorder: UnderlineInputBorder(borderSide: BorderSide(color: context.theme.backgroundColor, width: 0)),
),
)),`

**Comment by GotJimmy** [comment]
Just tried your code (without the styling and emailController) and it seems to work just fine on an Android emulator:

`    AccordionSection(
            isOpen: false,
            leftIcon: Icon(Icons.tag, color: Colors.black),
            header: Text('Details'),
            content: TextFormField(
              autofocus: false,
              cursorColor: Get.isDarkMode ? Colors.grey[100] : Colors.grey[700],
              // controller: _emailController,
              // style: subTitleStyle,
              decoration: InputDecoration(
                hintText: 'Enter Your Email',
                // hintStyle: subTitleStyle,
                focusedBorder: UnderlineInputBorder(borderSide: BorderSide(color: context.theme.backgroundColor, width: 0)),
                enabledBorder: UnderlineInputBorder(borderSide: BorderSide(color: context.theme.backgroundColor, width: 0)),
              ),
            )),

https://user-images.githubusercontent.com/6039735/146403175-d031a6ce-d273-4d5f-a867-3b6efd95a3da.mov

`

**Comment by GotJimmy** [comment]
> I also faced the same issue. I have done using the observables. Maybe that can be an issue. Can you please look into it?

Can you send me the relevant code so I can see what the problem is.
