### ISSUE TITLE
setState() or markNeedsBuild() called during build. Please add rebuild key or something

### ISSUE THREAD

**Issue by bugthug404** [GotJimmy/accordion#9]
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Accordion(dirty):
setState() or markNeedsBuild() called during build.

This Obx widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: Obx
    has builder
    dirty
    state: _ObxState#23bef
The widget which was currently being built when the offending call was made was: Accordion
    dirty
The relevant error-causing widget was
Accordion
lib\screens\home_page.dart:31

**Comment by GotJimmy** [comment]
Can you please post an example where this happens? Thanks.
